version: '3'
services:
  proto:
    container_name: proto
    build:
      context: .
      dockerfile: ./docker/proto/Dockerfile
    stdin_open: true
    tty: true   
    volumes:
      - .:/proto
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./server:/go/src/grpc-web
    ports:
      - "9090:9090"
    depends_on:
      - proto
  envoy:
    container_name: envoy-grpc-proxy
    build:
      context: .
      dockerfile: ./docker/envoy/Dockerfile
    ports:
      - "8080:8080"
    links:
      - "server"