version: '3'
services:
  proto:
    container_name: proto
    build:
      context: ./docker/proto
      dockerfile: Dockerfile
    stdin_open: true
    tty: true   
    volumes:
      - .:/proto
  server:
    container_name: server
    build:
      context: ./docker/server
      dockerfile: Dockerfile
    volumes:
      - ./server:/go/src/grpc-web
    ports:
      - "8080:8080"
    depends_on:
      - proto
   